export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/intro.html.js"), meta: {"title":"Pagina de apresentação","icon":"circle-info"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"Inicio","icon":"house"} }],
  ["/posts/01_links_uteis.html", { loader: () => import(/* webpackChunkName: "posts_01_links_uteis.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/01_links_uteis.html.js"), meta: {"date":1744026000000,"category":["multimidia"],"tag":["links"],"readingTime":{"minutes":1.97,"words":591},"title":"Montando Ambiente de trabalho","icon":"edit","order":1,"type":"article"} }],
  ["/posts/02_introducao.html", { loader: () => import(/* webpackChunkName: "posts_02_introducao.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/02_introducao.html.js"), meta: {"date":1744026600000,"category":["aula"],"tag":["java","paradigmas"],"readingTime":{"minutes":12.47,"words":3740},"title":"Linguagens e paradigmas de programação","icon":"edit","order":2,"type":"article"} }],
  ["/posts/03_Codificando_JAVA.html", { loader: () => import(/* webpackChunkName: "posts_03_Codificando_JAVA.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/03_Codificando_JAVA.html.js"), meta: {"date":1744026900000,"category":["aula"],"tag":["java"],"readingTime":{"minutes":12.88,"words":3863},"title":"Codificando com JAVA","icon":"edit","order":3,"type":"article"} }],
  ["/posts/04_objeto_classe.html", { loader: () => import(/* webpackChunkName: "posts_04_objeto_classe.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/04_objeto_classe.html.js"), meta: {"date":1745060400000,"category":["aula"],"tag":["java","objeto","classe"],"readingTime":{"minutes":5.56,"words":1668},"title":"Programação Orientada a Objetos","icon":"edit","order":4,"type":"article"} }],
  ["/posts/05_Construtor.html", { loader: () => import(/* webpackChunkName: "posts_05_Construtor.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/05_Construtor.html.js"), meta: {"date":1745706000000,"category":["aula"],"tag":["construtor"],"readingTime":{"minutes":1.01,"words":304},"title":"Construtor","icon":"edit","order":5,"type":"article"} }],
  ["/posts/06_uml.html", { loader: () => import(/* webpackChunkName: "posts_06_uml.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/06_uml.html.js"), meta: {"date":1748860200000,"category":["aula"],"tag":["UML"],"readingTime":{"minutes":1.1,"words":331},"title":"UML","icon":"edit","order":6,"type":"article"} }],
  ["/posts/07_associacoes.html", { loader: () => import(/* webpackChunkName: "posts_07_associacoes.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/07_associacoes.html.js"), meta: {"date":1748860800000,"category":["aula"],"tag":["associacao","agregacao","composicao"],"readingTime":{"minutes":1.03,"words":308},"title":"Associações","icon":"edit","order":7,"type":"article"} }],
  ["/posts/08_ArrayList.html", { loader: () => import(/* webpackChunkName: "posts_08_ArrayList.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/08_ArrayList.html.js"), meta: {"date":1752489000000,"category":["aula"],"tag":["vetor","lista"],"readingTime":{"minutes":2.71,"words":812},"title":"Trabalhando com ArrayList","icon":"edit","order":8,"type":"article"} }],
  ["/posts/09_encapsulamento.html", { loader: () => import(/* webpackChunkName: "posts_09_encapsulamento.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/09_encapsulamento.html.js"), meta: {"date":1753096800000,"category":["aula"],"tag":["pacote","encapsulamento","construtor"],"readingTime":{"minutes":3.44,"words":1033},"title":"Encapsulamento","icon":"edit","order":9,"type":"article"} }],
  ["/posts/10_datas.html", { loader: () => import(/* webpackChunkName: "posts_10_datas.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/10_datas.html.js"), meta: {"date":1753700400000,"category":["aula"],"tag":["java","datas"],"readingTime":{"minutes":2.77,"words":830},"title":"API de data do Java","icon":"edit","order":10,"type":"article"} }],
  ["/posts/11_heranca.html", { loader: () => import(/* webpackChunkName: "posts_11_heranca.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/11_heranca.html.js"), meta: {"date":1753700460000,"category":["aula"],"tag":["heranca"],"readingTime":{"minutes":16.79,"words":5037},"title":"Herança","icon":"edit","order":12,"type":"article"} }],
  ["/posts/12_greenfoot.html", { loader: () => import(/* webpackChunkName: "posts_12_greenfoot.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/12_greenfoot.html.js"), meta: {"date":1754910060000,"category":["aula"],"tag":["heranca","entrega"],"readingTime":{"minutes":14.44,"words":4332},"title":"Geenfoot","icon":"edit","order":13,"type":"article"} }],
  ["/posts/13_greenfoot_jogo.html", { loader: () => import(/* webpackChunkName: "posts_13_greenfoot_jogo.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/13_greenfoot_jogo.html.js"), meta: {"date":1756123200000,"category":["trabalho"],"tag":["greenfoot","jogo"],"readingTime":{"minutes":4.35,"words":1306},"title":"Criando um Jogo no Estilo Hole.io","icon":"edit","order":14,"type":"article"} }],
  ["/posts/14_jogo_etapa2.html", { loader: () => import(/* webpackChunkName: "posts_14_jogo_etapa2.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/14_jogo_etapa2.html.js"), meta: {"date":1757932200000,"category":["trabalho"],"tag":["greenfoot","jogo"],"readingTime":{"minutes":2.57,"words":772},"title":"Exercício de Refatoração: Otimizando o Jogo \"Hole.io\" com Orientação a Objetos","icon":"edit","order":15,"type":"article"} }],
  ["/posts/15_polimorfismo.html", { loader: () => import(/* webpackChunkName: "posts_15_polimorfismo.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/15_polimorfismo.html.js"), meta: {"date":1762771200000,"category":["aula"],"tag":["polimorfismo"],"readingTime":{"minutes":6.88,"words":2063},"title":"Polimorfismo","icon":"edit","order":15,"type":"article"} }],
  ["/posts/16_abstratas_interface.html", { loader: () => import(/* webpackChunkName: "posts_16_abstratas_interface.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/16_abstratas_interface.html.js"), meta: {"date":1762774800000,"category":["aula"],"tag":["classes-abstratas","interface"],"readingTime":{"minutes":10.97,"words":3291},"title":"Classes Abstratas e Interface","icon":"edit","order":16,"type":"article"} }],
  ["/posts/17_Exceptions.html", { loader: () => import(/* webpackChunkName: "posts_17_Exceptions.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/17_Exceptions.html.js"), meta: {"date":1764018000000,"category":["aula"],"tag":["exception"],"readingTime":{"minutes":4.19,"words":1256},"title":"Exceptions","icon":"edit","order":17,"type":"article"} }],
  ["/posts/ementa.html", { loader: () => import(/* webpackChunkName: "posts_ementa.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/ementa.html.js"), meta: {"date":1743417600000,"category":["Plano de Curso"],"tag":["ementa"],"readingTime":{"minutes":1.41,"words":423},"title":"Plano de Curso","icon":"edit","index":false,"type":"article"} }],
  ["/posts/print.html", { loader: () => import(/* webpackChunkName: "posts_print.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/print.html.js"), meta: {"title":"Versão para Impressão","icon":"print","index":false} }],
  ["/posts/subjectRecoII.html", { loader: () => import(/* webpackChunkName: "posts_subjectRecoII.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/subjectRecoII.html.js"), meta: {"title":"Versão para Impressão","icon":"print","index":false} }],
  ["/posts/exercicios/00_exercicio_java_w3c.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_00_exercicio_java_w3c.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/00_exercicio_java_w3c.html.js"), meta: {"date":1744627211000,"category":["exercicio"],"tag":["java"],"readingTime":{"minutes":0.08,"words":24},"title":"Exercício Java no W3C","icon":"dumbbell","order":1,"type":"article"} }],
  ["/posts/exercicios/01_exercicio_java_caelum.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_01_exercicio_java_caelum.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/01_exercicio_java_caelum.html.js"), meta: {"date":1744627511000,"category":["exercicio","entrega"],"tag":["java"],"readingTime":{"minutes":1.33,"words":399},"title":"Exercício: Fixação de sintaxe","icon":"dumbbell","order":2,"type":"article"} }],
  ["/posts/exercicios/02_exercicio_data_OO.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_02_exercicio_data_OO.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/02_exercicio_data_OO.html.js"), meta: {"date":1744631111000,"category":["exercicio"],"tag":["java"],"readingTime":{"minutes":0.45,"words":136},"title":"Exercício: Data OO","icon":"dumbbell","order":3,"type":"article"} }],
  ["/posts/exercicios/03_exercicio_modelagem_carro.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_03_exercicio_modelagem_carro.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/03_exercicio_modelagem_carro.html.js"), meta: {"date":1747056000000,"category":["exercicio","entrega"],"tag":["java"],"readingTime":{"minutes":0.27,"words":81},"title":"Exercício: Modelagem Carro","icon":"dumbbell","order":4,"type":"article"} }],
  ["/posts/exercicios/04_exercicio_modelagem_tv.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_04_exercicio_modelagem_tv.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/04_exercicio_modelagem_tv.html.js"), meta: {"date":1747057200000,"category":["exercicio"],"tag":["java"],"readingTime":{"minutes":0.44,"words":131},"title":"Exercício: Modelagem TV","icon":"dumbbell","order":5,"type":"article"} }],
  ["/posts/exercicios/05_exercicio_modelagem_dvd.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_05_exercicio_modelagem_dvd.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/05_exercicio_modelagem_dvd.html.js"), meta: {"date":1748861700000,"category":["exercicio"],"tag":["java"],"readingTime":{"minutes":0.96,"words":288},"title":"Exercício: Modelagem DVD","icon":"dumbbell","order":6,"type":"article"} }],
  ["/posts/exercicios/06_exercicio_predio_OO.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_06_exercicio_predio_OO.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/06_exercicio_predio_OO.html.js"), meta: {"date":1748865300000,"category":["exercicio"],"tag":["java"],"readingTime":{"minutes":0.22,"words":66},"title":"Exercício: Area do Prédio OO","icon":"dumbbell","order":7,"type":"article"} }],
  ["/posts/exercicios/07_exercicio_modelagem_computador.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_07_exercicio_modelagem_computador.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/07_exercicio_modelagem_computador.html.js"), meta: {"date":1748862000000,"category":["exercicio"],"tag":["java"],"readingTime":{"minutes":0.64,"words":191},"title":"Exercício: Modelagem Computador","icon":"dumbbell","order":8,"type":"article"} }],
  ["/posts/exercicios/08_exercicio_sistema_banco.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_08_exercicio_sistema_banco.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/08_exercicio_sistema_banco.html.js"), meta: {"date":1752490800000,"category":["exercicio","entrega"],"tag":["java"],"readingTime":{"minutes":0.41,"words":124},"title":"Exercício: Modelagem Sistema Banco","icon":"dumbbell","order":9,"type":"article"} }],
  ["/posts/exercicios/09_exercicio_modelagem_tv_encapsulamento.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_09_exercicio_modelagem_tv_encapsulamento.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/09_exercicio_modelagem_tv_encapsulamento.html.js"), meta: {"date":1753096860000,"category":["entrega","exercicio"],"tag":["java"],"readingTime":{"minutes":0.54,"words":161},"title":"Exercício Encapsulamento: Modelagem TV","icon":"dumbbell","order":10,"type":"article"} }],
  ["/posts/exercicios/10_exercicio_modelagem_dvd_encapsulamento.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_10_exercicio_modelagem_dvd_encapsulamento.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/10_exercicio_modelagem_dvd_encapsulamento.html.js"), meta: {"date":1753096920000,"category":["exercicio","entrega"],"tag":["java"],"readingTime":{"minutes":0.85,"words":255},"title":"Exercício Encapsulamento: Modelagem DVD","icon":"dumbbell","order":11,"type":"article"} }],
  ["/posts/exercicios/11_exercicio_Heranca1.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_11_exercicio_Heranca1.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/11_exercicio_Heranca1.html.js"), meta: {"date":1753700520000,"category":["exercicio"],"tag":["heranca"],"readingTime":{"minutes":0.58,"words":174},"title":"Exercício de Herança 1","icon":"dumbbell","order":12,"type":"article"} }],
  ["/posts/exercicios/12_exercicio_Heranca2.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_12_exercicio_Heranca2.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/12_exercicio_Heranca2.html.js"), meta: {"date":1754305320000,"category":["exercicio","pratica","entrega"],"tag":["heranca"],"readingTime":{"minutes":1.06,"words":319},"title":"Exercício de Herança 2","icon":"dumbbell","order":12,"type":"article"} }],
  ["/posts/exercicios/13_exercicio_Heranca3Extenso.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_13_exercicio_Heranca3Extenso.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/13_exercicio_Heranca3Extenso.html.js"), meta: {"date":1754305380000,"category":["exercicio","entrega"],"tag":["heranca"],"readingTime":{"minutes":0.53,"words":160},"title":"Exercício Herança 3: Converter para Extenso","icon":"dumbbell","order":13,"type":"article"} }],
  ["/posts/exercicios/14_exercicio_Heranca4%20Banco.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_14_exercicio_Heranca4 Banco.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/14_exercicio_Heranca4 Banco.html.js"), meta: {"date":1754305500000,"category":["exercicio"],"tag":["heranca"],"readingTime":{"minutes":1.55,"words":466},"title":"Exercício de Herança 4 (Sistema banco)","icon":"dumbbell","order":14,"type":"article"} }],
  ["/posts/exercicios/15_exercicio_modelagem_listas.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_15_exercicio_modelagem_listas.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/15_exercicio_modelagem_listas.html.js"), meta: {"date":1759748400000,"category":["exercicio"],"tag":["java"],"readingTime":{"minutes":4.92,"words":1477},"title":"Exercícios Listas","icon":"dumbbell","order":15,"type":"article"} }],
  ["/posts/exercicios/16_exercicio_exercito_simplificado.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_16_exercicio_exercito_simplificado.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/16_exercicio_exercito_simplificado.html.js"), meta: {"date":1759749000000,"category":["exercicio","entrega"],"tag":["java"],"readingTime":{"minutes":0.38,"words":113},"title":"Hierarquia Militar Simplificada","icon":"dumbbell","order":16,"type":"article"} }],
  ["/posts/exercicios/17_exercicio_Polimorfismo1.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_17_exercicio_Polimorfismo1.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/17_exercicio_Polimorfismo1.html.js"), meta: {"date":1762776000000,"category":["exercicio"],"tag":["heranca","polimorfismo"],"readingTime":{"minutes":1.28,"words":384},"title":"Exercício Polimorfismo","icon":"dumbbell","order":17,"type":"article"} }],
  ["/posts/exercicios/18_exercicio_AbstrataInterface.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_18_exercicio_AbstrataInterface.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/18_exercicio_AbstrataInterface.html.js"), meta: {"date":1762776600000,"category":["exercicio"],"tag":["heranca","abstratas","interface"],"readingTime":{"minutes":0.57,"words":172},"title":"Exercício Herança classes Abstratas e Interface","icon":"dumbbell","order":18,"type":"article"} }],
  ["/posts/exercicios/19_exercicio_exception_1.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_19_exercicio_exception_1.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/19_exercicio_exception_1.html.js"), meta: {"date":1764021600000,"category":["exercicio"],"tag":["exception"],"readingTime":{"minutes":0.43,"words":128},"title":"Exercícios sobre Exception (IllegalArgumentException, SaldoInsufucienteException)","icon":"dumbbell","order":19,"type":"article"} }],
  ["/posts/exercicios/20_exercicio_exception_2.html", { loader: () => import(/* webpackChunkName: "posts_exercicios_20_exercicio_exception_2.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/20_exercicio_exception_2.html.js"), meta: {"date":1764021660000,"category":["exercicio","entrega"],"tag":["exception"],"readingTime":{"minutes":0.52,"words":156},"title":"Exercício AutenticacaoInvalidaException","icon":"dumbbell","order":20,"type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"title":"Posts"} }],
  ["/posts/exercicios/", { loader: () => import(/* webpackChunkName: "posts_exercicios_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/posts/exercicios/index.html.js"), meta: {"title":"Exercicios"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"Category","index":false} }],
  ["/category/multimidia/", { loader: () => import(/* webpackChunkName: "category_multimidia_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/multimidia/index.html.js"), meta: {"title":"multimidia Category","index":false} }],
  ["/category/aula/", { loader: () => import(/* webpackChunkName: "category_aula_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/aula/index.html.js"), meta: {"title":"aula Category","index":false} }],
  ["/category/trabalho/", { loader: () => import(/* webpackChunkName: "category_trabalho_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/trabalho/index.html.js"), meta: {"title":"trabalho Category","index":false} }],
  ["/category/plano-de-curso/", { loader: () => import(/* webpackChunkName: "category_plano-de-curso_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/plano-de-curso/index.html.js"), meta: {"title":"Plano de Curso Category","index":false} }],
  ["/category/exercicio/", { loader: () => import(/* webpackChunkName: "category_exercicio_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/exercicio/index.html.js"), meta: {"title":"exercicio Category","index":false} }],
  ["/category/entrega/", { loader: () => import(/* webpackChunkName: "category_entrega_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/entrega/index.html.js"), meta: {"title":"entrega Category","index":false} }],
  ["/category/pratica/", { loader: () => import(/* webpackChunkName: "category_pratica_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/category/pratica/index.html.js"), meta: {"title":"pratica Category","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"Tag","index":false} }],
  ["/tag/links/", { loader: () => import(/* webpackChunkName: "tag_links_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/links/index.html.js"), meta: {"title":"Tag: links","index":false} }],
  ["/tag/java/", { loader: () => import(/* webpackChunkName: "tag_java_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/java/index.html.js"), meta: {"title":"Tag: java","index":false} }],
  ["/tag/paradigmas/", { loader: () => import(/* webpackChunkName: "tag_paradigmas_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/paradigmas/index.html.js"), meta: {"title":"Tag: paradigmas","index":false} }],
  ["/tag/objeto/", { loader: () => import(/* webpackChunkName: "tag_objeto_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/objeto/index.html.js"), meta: {"title":"Tag: objeto","index":false} }],
  ["/tag/classe/", { loader: () => import(/* webpackChunkName: "tag_classe_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/classe/index.html.js"), meta: {"title":"Tag: classe","index":false} }],
  ["/tag/construtor/", { loader: () => import(/* webpackChunkName: "tag_construtor_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/construtor/index.html.js"), meta: {"title":"Tag: construtor","index":false} }],
  ["/tag/uml/", { loader: () => import(/* webpackChunkName: "tag_uml_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/uml/index.html.js"), meta: {"title":"Tag: UML","index":false} }],
  ["/tag/associacao/", { loader: () => import(/* webpackChunkName: "tag_associacao_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/associacao/index.html.js"), meta: {"title":"Tag: associacao","index":false} }],
  ["/tag/agregacao/", { loader: () => import(/* webpackChunkName: "tag_agregacao_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/agregacao/index.html.js"), meta: {"title":"Tag: agregacao","index":false} }],
  ["/tag/composicao/", { loader: () => import(/* webpackChunkName: "tag_composicao_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/composicao/index.html.js"), meta: {"title":"Tag: composicao","index":false} }],
  ["/tag/vetor/", { loader: () => import(/* webpackChunkName: "tag_vetor_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/vetor/index.html.js"), meta: {"title":"Tag: vetor","index":false} }],
  ["/tag/lista/", { loader: () => import(/* webpackChunkName: "tag_lista_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/lista/index.html.js"), meta: {"title":"Tag: lista","index":false} }],
  ["/tag/pacote/", { loader: () => import(/* webpackChunkName: "tag_pacote_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/pacote/index.html.js"), meta: {"title":"Tag: pacote","index":false} }],
  ["/tag/encapsulamento/", { loader: () => import(/* webpackChunkName: "tag_encapsulamento_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/encapsulamento/index.html.js"), meta: {"title":"Tag: encapsulamento","index":false} }],
  ["/tag/datas/", { loader: () => import(/* webpackChunkName: "tag_datas_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/datas/index.html.js"), meta: {"title":"Tag: datas","index":false} }],
  ["/tag/heranca/", { loader: () => import(/* webpackChunkName: "tag_heranca_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/heranca/index.html.js"), meta: {"title":"Tag: heranca","index":false} }],
  ["/tag/entrega/", { loader: () => import(/* webpackChunkName: "tag_entrega_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/entrega/index.html.js"), meta: {"title":"Tag: entrega","index":false} }],
  ["/tag/greenfoot/", { loader: () => import(/* webpackChunkName: "tag_greenfoot_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/greenfoot/index.html.js"), meta: {"title":"Tag: greenfoot","index":false} }],
  ["/tag/jogo/", { loader: () => import(/* webpackChunkName: "tag_jogo_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/jogo/index.html.js"), meta: {"title":"Tag: jogo","index":false} }],
  ["/tag/polimorfismo/", { loader: () => import(/* webpackChunkName: "tag_polimorfismo_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/polimorfismo/index.html.js"), meta: {"title":"Tag: polimorfismo","index":false} }],
  ["/tag/classes-abstratas/", { loader: () => import(/* webpackChunkName: "tag_classes-abstratas_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/classes-abstratas/index.html.js"), meta: {"title":"Tag: classes-abstratas","index":false} }],
  ["/tag/interface/", { loader: () => import(/* webpackChunkName: "tag_interface_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/interface/index.html.js"), meta: {"title":"Tag: interface","index":false} }],
  ["/tag/exception/", { loader: () => import(/* webpackChunkName: "tag_exception_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/exception/index.html.js"), meta: {"title":"Tag: exception","index":false} }],
  ["/tag/ementa/", { loader: () => import(/* webpackChunkName: "tag_ementa_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/ementa/index.html.js"), meta: {"title":"Tag: ementa","index":false} }],
  ["/tag/abstratas/", { loader: () => import(/* webpackChunkName: "tag_abstratas_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/tag/abstratas/index.html.js"), meta: {"title":"Tag: abstratas","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"Articles","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"Star","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/IFBA/20250IntPoo/blog/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"Timeline","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
