@startuml
class Aluno {
    - String matricula
    - String nome
    - List<Turma> turmas
}

class Professor {
    - String SIAPE
    - String nome
    - List<Turma> turmas
}

class Turma {
    - String id
    - String nome
    - List<Professor> professores
    - List<Aluno> alunos
}
Turma .. Aluno
Turma .. Professor
@enduml
