<template><div><h1 id="greenfoot" tabindex="-1"><a class="header-anchor" href="#greenfoot"><span>Greenfoot</span></a></h1>
<p>Imagine que você quer construir uma peça de teatro. Você precisa de um <strong>palco</strong> (o cenário onde tudo acontece) e de <strong>atores</strong> (os personagens que executam as ações). O Greenfoot funciona exatamente assim.</p>
<ul>
<li><strong>World (Mundo):</strong> É o palco. É a classe que representa o cenário do seu jogo (uma floresta, o espaço, uma quadra de futebol).</li>
<li><strong>Actor (Ator):</strong> São os personagens e objetos no palco. O herói, o inimigo, uma moeda, uma parede, tudo que tem comportamento ou interage com algo é um Ator.</li>
</ul>
<p>O Greenfoot nos permite programar em <strong>Java</strong>, uma das linguagens mais usadas no mundo, mas de uma forma muito mais visual e intuitiva. Ele remove as partes complexas e repetitivas para que possamos focar na lógica e na criatividade.</p>
<h4 id="_1-3-explorando-a-interface" tabindex="-1"><a class="header-anchor" href="#_1-3-explorando-a-interface"><span><strong>1.3. Explorando a Interface</strong></span></a></h4>
<p>Ao abrir o Greenfoot, você verá:</p>
<ol>
<li><strong>O Mundo (Centro):</strong> A grade grande onde seu jogo irá rodar.</li>
<li><strong>Diagrama de Classes (Direita):</strong> A representação visual do seu código. Você verá as caixas <code v-pre>World</code> e <code v-pre>Actor</code> e as classes que você criar herdarão delas.</li>
<li><strong>Controles de Execução (Abaixo):</strong> Os botões <code v-pre>Act</code> (executa um passo da lógica) e <code v-pre>Run</code> (executa continuamente).</li>
</ol>
<figure><img src="https://www.greenfoot.org/images/screens/greenfoot-screen-3.6.1.png" alt="Interface Conceitual do Greenfoot" tabindex="0" loading="lazy"><figcaption>Interface Conceitual do Greenfoot</figcaption></figure>
<h4 id="_1-4-atividade-hands-on-o-wombat-e-a-folha" tabindex="-1"><a class="header-anchor" href="#_1-4-atividade-hands-on-o-wombat-e-a-folha"><span><strong>1.4. Atividade Hands-On: O Wombat e a Folha</strong></span></a></h4>
<p>O Greenfoot vem com cenários de exemplo. Vamos usar o &quot;Wombats&quot;.</p>
<ol>
<li>Abra o cenário <code v-pre>wombats</code>.</li>
<li>No Diagrama de Classes, clique com o botão direito na classe <code v-pre>Wombat</code> e selecione <code v-pre>new Wombat()</code>.</li>
<li>Clique em qualquer lugar do mundo para adicionar um Wombat.</li>
<li>Faça o mesmo com a classe <code v-pre>Leaf</code> (Folha).</li>
<li><strong>Interação Manual:</strong> Clique com o botão direito no objeto Wombat que você criou no mundo. Você verá um menu de &quot;ações&quot; (métodos) que ele pode executar, como <code v-pre>move()</code> e <code v-pre>turnLeft()</code>. Experimente chamá-los!</li>
<li><strong>Execução Automática:</strong> Clique no botão <code v-pre>Run</code>. O que acontece?</li>
</ol>
<h4 id="_1-5-reflexao" tabindex="-1"><a class="header-anchor" href="#_1-5-reflexao"><span><strong>1.5. Reflexão</strong></span></a></h4>
<ul>
<li>O que você acha que o botão <code v-pre>Act</code> faz? E o <code v-pre>Run</code>?</li>
<li>Qual a diferença entre a <strong>classe</strong> <code v-pre>Wombat</code> (no diagrama) e o <strong>objeto</strong> Wombat (no mundo)?</li>
</ul>
<hr>
<h3 id="modulo-2-fundamentos-de-programacao-orientada-a-objetos-poo" tabindex="-1"><a class="header-anchor" href="#modulo-2-fundamentos-de-programacao-orientada-a-objetos-poo"><span><strong>Módulo 2: Fundamentos de Programação Orientada a Objetos (POO)</strong></span></a></h3>
<h4 id="_2-1-objetivos-de-aprendizagem" tabindex="-1"><a class="header-anchor" href="#_2-1-objetivos-de-aprendizagem"><span><strong>2.1. Objetivos de Aprendizagem</strong></span></a></h4>
<ul>
<li>Entender o que são Classes e Objetos usando analogias.</li>
<li>Aprender o que são Atributos e Métodos.</li>
<li>Escrever seu primeiro código em Java usando o método <code v-pre>act()</code>.</li>
</ul>
<h4 id="_2-2-classes-e-objetos-a-forma-de-bolo" tabindex="-1"><a class="header-anchor" href="#_2-2-classes-e-objetos-a-forma-de-bolo"><span><strong>2.2. Classes e Objetos: A Forma de Bolo</strong></span></a></h4>
<p>Este é o conceito mais importante da POO.</p>
<ul>
<li><strong>Classe:</strong> É a <strong>receita</strong> ou a <strong>forma de um bolo</strong>. Ela define todas as características e comportamentos que algo pode ter. Por exemplo, a classe <code v-pre>Cachorro</code> define que todo cachorro tem uma raça, uma cor, e sabe latir.</li>
<li><strong>Objeto:</strong> É a <strong>instância</strong> da classe. É o <strong>bolo pronto</strong>, feito a partir da receita. Você pode ter vários objetos da mesma classe: <code v-pre>rex</code> (um <code v-pre>Cachorro</code> marrom), <code v-pre>toby</code> (um <code v-pre>Cachorro</code> branco), etc. Cada um é um objeto independente, mas ambos vieram da mesma &quot;forma&quot;.</li>
</ul>
<p>No Greenfoot, <code v-pre>Wombat</code> é a classe. Quando você cria um <code v-pre>new Wombat()</code>, está criando um objeto daquela classe.</p>
<h4 id="_2-3-atributos-e-metodos-o-que-eles-tem-e-o-que-eles-fazem" tabindex="-1"><a class="header-anchor" href="#_2-3-atributos-e-metodos-o-que-eles-tem-e-o-que-eles-fazem"><span><strong>2.3. Atributos e Métodos: O que eles Têm e o que eles Fazem</strong></span></a></h4>
<ul>
<li><strong>Atributos (ou Campos):</strong> São as <strong>características</strong> de um objeto, suas variáveis internas. Para um <code v-pre>Jogador</code>, os atributos podem ser <code v-pre>vida</code>, <code v-pre>pontuacao</code>, <code v-pre>velocidade</code>. Cada objeto guarda seus próprios valores para seus atributos.</li>
<li><strong>Métodos:</strong> São as <strong>ações</strong> que um objeto pode executar. Para um <code v-pre>Jogador</code>, os métodos podem ser <code v-pre>mover()</code>, <code v-pre>atirar()</code>, <code v-pre>perderVida()</code>.</li>
</ul>
<h4 id="_2-4-atividade-hands-on-fazendo-o-ator-se-mover-sozinho" tabindex="-1"><a class="header-anchor" href="#_2-4-atividade-hands-on-fazendo-o-ator-se-mover-sozinho"><span><strong>2.4. Atividade Hands-On: Fazendo o Ator se Mover Sozinho</strong></span></a></h4>
<ol>
<li>
<p>Crie um novo cenário vazio em Greenfoot (<code v-pre>Scenario &gt; New Java Scenario...</code>).</p>
</li>
<li>
<p>Crie uma nova subclasse de <code v-pre>Actor</code>. Chame-a de <code v-pre>Nave</code>. Escolha uma imagem de foguete para ela.</p>
</li>
<li>
<p>Dê um duplo clique na classe <code v-pre>Nave</code> para abrir o editor de código. Você verá algo assim:</p>
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">import</span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B"> greenfoot.</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">*</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> class</span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B"> Nave</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> extends</span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B"> Actor</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">{</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">    /**</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">     * Act - do whatever the Nave wants to do. This method is called whenever</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">     * the 'Act' or 'Run' buttons are pressed in the environment.</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">     */</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> act</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    {</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">        // Adicione seu código de ação aqui.</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>Dentro do método <code v-pre>act()</code>, digite <code v-pre>move(5);</code>. O método <code v-pre>move()</code> é um método que todo <code v-pre>Actor</code> já possui por herança!</p>
</li>
<li>
<p>Clique em <strong>Compile</strong> no editor.</p>
</li>
<li>
<p>Agora, adicione um objeto <code v-pre>Nave</code> ao mundo e clique em <code v-pre>Run</code>. Ela se move sozinha!</p>
</li>
</ol>
<h4 id="_2-5-reflexao" tabindex="-1"><a class="header-anchor" href="#_2-5-reflexao"><span><strong>2.5. Reflexão</strong></span></a></h4>
<ul>
<li>O que aconteceria se você mudasse o número dentro de <code v-pre>move()</code>?</li>
<li>Como você faria a nave virar um pouco a cada &quot;ato&quot;? (Dica: existe um método <code v-pre>turn()</code>).</li>
</ul>
<hr>
<h3 id="modulo-3-tutorial-pratico-jogo-guerra-espacial" tabindex="-1"><a class="header-anchor" href="#modulo-3-tutorial-pratico-jogo-guerra-espacial"><span><strong>Módulo 3: Tutorial Prático - Jogo &quot;Guerra Espacial&quot;</strong></span></a></h3>
<p>Vamos construir um jogo de nave completo, aplicando todos os conceitos de POO.</p>
<h4 id="parte-1-criando-o-mundo-e-a-nave-do-jogador" tabindex="-1"><a class="header-anchor" href="#parte-1-criando-o-mundo-e-a-nave-do-jogador"><span><strong>Parte 1: Criando o Mundo e a Nave do Jogador</strong></span></a></h4>
<ol>
<li><strong>O Mundo:</strong> Crie uma subclasse de <code v-pre>World</code> chamada <code v-pre>Espaco</code>. No construtor dela, podemos definir o tamanho e a cor de fundo.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Dentro da classe Espaco.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> Espaco</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">    super</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">800</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 600</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> // Largura, Altura, Tamanho da célula</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    getBackground</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">setColor</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">Color</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">BLACK</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    getBackground</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">fill</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">();</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li><strong>A Nave:</strong> Já criamos a classe <code v-pre>Nave</code>. Agora, vamos fazer ela ser controlada pelo teclado.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Dentro do método act() da classe Nave.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> act</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    if</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">Greenfoot</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">isKeyDown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"left"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    {</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        turn</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">-</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">5</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    if</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">Greenfoot</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">isKeyDown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"right"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    {</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        turn</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">5</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    if</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">Greenfoot</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">isKeyDown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"up"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    {</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        move</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">5</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><strong>Conceito-Chave:</strong> Estamos usando <code v-pre>if</code> (estruturas de controle) para verificar uma condição (se uma tecla está pressionada) e executar uma ação.</li>
</ol>
<h4 id="parte-2-atirando-lasers-criacao-de-objetos" tabindex="-1"><a class="header-anchor" href="#parte-2-atirando-lasers-criacao-de-objetos"><span><strong>Parte 2: Atirando Lasers (Criação de Objetos)</strong></span></a></h4>
<ol>
<li><strong>Classe Laser:</strong> Crie uma nova classe <code v-pre>Actor</code> chamada <code v-pre>Laser</code>. A única coisa que ela precisa fazer é se mover para cima.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Dentro do método act() da classe Laser.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> act</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    move</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">10</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">    // Lógica para remover o laser quando ele sai da tela (veremos depois)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li><strong>Fazendo a Nave Atirar:</strong> Como a <code v-pre>Nave</code> cria um <code v-pre>Laser</code>? Ela precisa instanciar um novo objeto <code v-pre>Laser</code> e adicioná-lo ao mundo.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Adicione este código DENTRO do método act() da Nave.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">if</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">Greenfoot</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">isKeyDown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"space"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    getWorld</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">addObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">new</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> Laser</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(), </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">getX</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(), </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">getY</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">());</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><strong>Conceito-Chave:</strong> <code v-pre>new Laser()</code> cria um novo objeto. <code v-pre>getWorld().addObject()</code> o coloca no mundo na posição <code v-pre>(getX(), getY())</code> da nave.</li>
</ol>
<h4 id="parte-3-inimigos-e-colisao" tabindex="-1"><a class="header-anchor" href="#parte-3-inimigos-e-colisao"><span><strong>Parte 3: Inimigos e Colisão</strong></span></a></h4>
<ol>
<li><strong>Classe Inimigo:</strong> Crie um <code v-pre>Actor</code> chamado <code v-pre>Inimigo</code>. Faça ele se mover para baixo.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Dentro do método act() da classe Inimigo.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> act</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    move</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">3</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li><strong>Gerando Inimigos:</strong> O <code v-pre>Espaco</code> (nosso <code v-pre>World</code>) é o responsável por gerar inimigos de tempos em tempos.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Dentro do método act() da classe Espaco.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> act</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    if</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">Greenfoot</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">getRandomNumber</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">100</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> &#x3C;</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    {</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        addObject</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">new</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> Inimigo</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B"> Greenfoot</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">getRandomNumber</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">800</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">),</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li><strong>Detectando Colisão:</strong> Como o <code v-pre>Laser</code> sabe que acertou um <code v-pre>Inimigo</code>?<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Dentro do método act() da classe Laser.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> act</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    move</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">10</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B">    Actor</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> inimigo </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> getOneIntersectingObject</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">Inimigo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">class</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    if</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (inimigo </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">!=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> null</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    {</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        getWorld</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">removeObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(inimigo);</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> // Remove o inimigo</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">        getWorld</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">removeObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">this</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">    // Remove o próprio laser</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><strong>Conceitos-Chave:</strong>
<ul>
<li><code v-pre>getOneIntersectingObject(Inimigo.class)</code>: Verifica se o laser está tocando em algum objeto da classe <code v-pre>Inimigo</code>.</li>
<li><code v-pre>!= null</code>: Significa &quot;se encontrou alguém&quot;.</li>
<li><code v-pre>removeObject()</code>: Tira um ator do mundo.</li>
</ul>
</li>
</ol>
<h4 id="parte-4-pontuacao-encapsulamento" tabindex="-1"><a class="header-anchor" href="#parte-4-pontuacao-encapsulamento"><span><strong>Parte 4: Pontuação (Encapsulamento)</strong></span></a></h4>
<ol>
<li><strong>Atributo de Pontuação:</strong> Onde guardar a pontuação? No <code v-pre>Mundo</code>! Ele gerencia o estado geral do jogo.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Adicione este atributo no topo da classe Espaco.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">private</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> int</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> score </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><strong>Pilar da POO (Encapsulamento):</strong> O <code v-pre>score</code> é <code v-pre>private</code>, ou seja, só a própria classe <code v-pre>Espaco</code> pode modificá-lo diretamente. Isso protege o dado de alterações indevidas.</li>
<li><strong>Método para Aumentar Pontos:</strong> Para que outros objetos possam alterar a pontuação, criamos um método público.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Adicione este método na classe Espaco.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> addScore</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">int</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> points)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">    score </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> score </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">+</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> points</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    showText</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Score: "</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> +</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> score</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 100</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 25</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> // Mostra o placar na tela</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li><strong>Chamando o Método:</strong> Agora, o <code v-pre>Laser</code>, quando destrói um inimigo, pode &quot;pedir&quot; ao mundo para adicionar pontos.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Modifique o if dentro do act() do Laser.java</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">if</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (inimigo </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">!=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> null</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">{</span></span>
<span class="line"><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B">    Espaco</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> espaco </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> (Espaco) </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">getWorld</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> // Pega a referência do mundo</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">    espaco</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">addScore</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">10</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> // Adiciona 10 pontos</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    getWorld</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">removeObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(inimigo);</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    getWorld</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">()</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">removeObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B">this</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
</ol>
<h4 id="parte-5-inimigos-diferentes-heranca-e-polimorfismo" tabindex="-1"><a class="header-anchor" href="#parte-5-inimigos-diferentes-heranca-e-polimorfismo"><span><strong>Parte 5: Inimigos Diferentes (Herança e Polimorfismo)</strong></span></a></h4>
<ol>
<li><strong>Classe InimigoChefe:</strong> Crie uma nova classe chamada <code v-pre>InimigoChefe</code>, mas desta vez, faça ela <strong>herdar de <code v-pre>Inimigo</code></strong>, não de <code v-pre>Actor</code>.<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> class</span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B"> InimigoChefe</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> extends</span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B"> Inimigo</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">{</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">    // Ele já sabe se mover, pois herdou isso do Inimigo!</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">    // Vamos apenas dar a ele mais vida (veremos como implementar isso nos exercícios)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><strong>Pilar da POO (Herança):</strong> <code v-pre>InimigoChefe</code> <strong>é um</strong> <code v-pre>Inimigo</code>. Ele herda todos os atributos e métodos da classe pai.</li>
<li><strong>Polimorfismo:</strong> A mágica acontece agora. O nosso <code v-pre>Laser</code> já sabe destruir o <code v-pre>InimigoChefe</code>! Por quê? Porque o método <code v-pre>getOneIntersectingObject(Inimigo.class)</code> detecta a classe <code v-pre>Inimigo</code> <strong>e qualquer uma de suas filhas</strong>. Ele trata o <code v-pre>InimigoChefe</code> como se fosse um <code v-pre>Inimigo</code>. Isso é Polimorfismo!</li>
</ol>
<hr>
<h3 id="modulo-4-proximos-passos-e-desafios" tabindex="-1"><a class="header-anchor" href="#modulo-4-proximos-passos-e-desafios"><span><strong>Módulo 4: Próximos Passos e Desafios</strong></span></a></h3>
<h4 id="_4-1-adicionando-sons" tabindex="-1"><a class="header-anchor" href="#_4-1-adicionando-sons"><span><strong>4.1. Adicionando Sons</strong></span></a></h4>
<ul>
<li>Use <code v-pre>Greenfoot.playSound(&quot;som.wav&quot;);</code> para tocar um efeito sonoro. Onde você colocaria o som do laser? E o da explosão?</li>
</ul>
<h4 id="_4-2-melhorando-a-interface" tabindex="-1"><a class="header-anchor" href="#_4-2-melhorando-a-interface"><span><strong>4.2. Melhorando a Interface</strong></span></a></h4>
<ul>
<li>Use o método <code v-pre>showText(&quot;Texto&quot;, x, y)</code> no seu <code v-pre>World</code> para criar uma tela de início ou de &quot;Game Over&quot;.</li>
</ul>
<h4 id="_4-3-onde-aprender-mais" tabindex="-1"><a class="header-anchor" href="#_4-3-onde-aprender-mais"><span><strong>4.3. Onde Aprender Mais?</strong></span></a></h4>
<ul>
<li><strong>Documentação Oficial do Greenfoot:</strong> A melhor fonte de consulta.</li>
<li><strong>Greenfoot Gallery:</strong> Veja projetos feitos por outras pessoas e estude o código delas.</li>
<li><strong>Comunidade Greenfoot:</strong> Participe de fóruns e tire suas dúvidas.</li>
</ul>
<hr>
</div></template>


